{
 "title": "UniFi: Client DPI",
 "description": "UniFi Poller v2.0 Displays DPI information for clients in a UniFi network using InfluxDB.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "show tag values from \"clientdpi\" with key=\"source\""
   },
   {
    "name": "Site",
    "query": "show tag values from \"clientdpi\" with key=\"site_name\" WHERE source =~ /^$Controller$/"
   },
   {
    "name": "Client",
    "query": "show tag values from \"clientdpi\" with key=\"name\" WHERE source =~ /^$Controller$/ AND site_name =~ /^$Site$/"
   },
   {
    "name": "Category",
    "query": "show tag values from \"clientdpi\" with key=\"category\" WHERE source =~ /^$Controller$/ AND site_name =~ /^$Site$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Help Wanted",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is very new and may contain errors. Please help me make it better. If you spot things that are inaccurate, [please report](https://github.com/unifi-poller/dashboards/issues/new) them! "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Totals  by Category",
   "type": "table",
   "description": "This shows lifetime rx+tx total and totals accumulated during the selected time range. The filters at the top of this page control _all_ of the graphs, and in some cases control the visibility of graphs. ie. Adding more clients displays more graphs under the collapsed Clients rows.",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "site_name" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "clientdpi",
     "query": "SELECT last(\"rx_bytes\") AS \"Bytes Rx Total\", last(\"tx_bytes\") AS \"Bytes Tx Total\" FROM \"clientdpi\" WHERE (\"site_name\" =~ /^$Site$/ AND \"name\" = 'TOTAL' AND \"category\" =~ /^$Category$/ AND \"application\" = 'TOTAL' AND \"mac\" = 'TOTAL') AND $timeFilter GROUP BY \"site_name\", \"category\", \"source\", \"application\", \"name\", \"mac\"",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx Total" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx Total" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Rx Packets" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Tx Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "name", "operator": "=", "value": "TOTAL" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$Category$/" },
      { "condition": "AND", "key": "application", "operator": "=", "value": "TOTAL" },
      { "condition": "AND", "key": "mac", "operator": "=", "value": "TOTAL" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic by Application",
   "type": "piechart",
   "description": "Showing traffic by app.\nThis updates with the variables on the dashboard.\nThis is grand totals and does not respect the time range, sorry. :(",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_category: $tag_application",
     "groupBy": [
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "clientdpi",
     "query": "SELECT last(\"rx_bytes\")+last(\"tx_bytes\") FROM \"clientdpi\" WHERE (\"category\" =~ /^$Category$/ AND \"source\" =~ /^$Controller$/ AND \"site_name\" =~ /^$Site$/ AND \"name\" =~ /^$Client$/ AND \"application\" != 'TOTAL') AND $timeFilter GROUP BY \"application\", \"category\"",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$Category$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
     ]
    }
   ]
  },
  {
   "title": "Total Traffic by Category",
   "type": "piechart",
   "description": "Showing traffic by cat.\nThis updates with the variables on the dashboard.\nThis is grand totals and does not respect the time range, sorry. :(",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_category: $tag_application",
     "groupBy": [
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "clientdpi",
     "query": "SELECT last(\"rx_bytes\")+last(\"tx_bytes\") FROM \"clientdpi\" WHERE (\"category\" =~ /^$Category$/ AND \"source\" =~ /^$Controller$/ AND \"site_name\" =~ /^$Site$/ AND \"name\" =~ /^$Client$/ AND \"application\" = 'TOTAL') AND $timeFilter GROUP BY \"application\", \"category\"",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$Category$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Transferred per Category",
   "type": "timeseries",
   "description": "Bytes Transferred by Category. Receive is on the negative axis.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_category $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "category" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" }
     ],
     "measurement": "clientdpi",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$Category$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
     ]
    }
   ]
  },
  {
   "title": "Packets Transferred  per Category",
   "type": "timeseries",
   "description": "Packets Transferred by Category. Receive is on the negative axis.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_category $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "category" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" }
     ],
     "measurement": "clientdpi",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$Category$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
     ]
    }
   ]
  },
  {
   "title": "Client Tx Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit Bytes - $Client",
     "type": "timeseries",
     "description": "Transmit Bytes per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "repeat": "Client",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Rx Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Bytes - $Client",
     "type": "timeseries",
     "description": "Receive Bytes per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "repeat": "Client",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Rx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Tx Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit Packets - $Client",
     "type": "timeseries",
     "description": "Transmitd Packets per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "repeat": "Client",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "tx_packets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Rx Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Packets - $Client",
     "type": "timeseries",
     "description": "Receive Packets per Application for $Client",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "repeat": "Client",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "rx_packets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$Category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "repeat": "Category",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit Bytes $Category",
     "type": "timeseries",
     "description": "Transmit Bytes per Application",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    },
    {
     "title": "Receive Bytes $Category",
     "type": "timeseries",
     "description": "Receive Bytes per Application",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    },
    {
     "title": "Receive Packets $Category",
     "type": "timeseries",
     "description": "Receive Packets per Application",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "rx_packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    },
    {
     "title": "Transmit Packets $Category",
     "type": "timeseries",
     "description": "Transmitted Packets per Application",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_application $tag_category",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "category" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "site_name" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "clientdpi",
       "select": [
        [
         { "params": [ "tx_packets" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "category", "operator": "=~", "value": "/^$Category$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Controller$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
        { "condition": "AND", "key": "application", "operator": "!=", "value": "TOTAL" }
       ]
      }
     ]
    }
   ]
  }
 ]
}