{
 "title": "UniFi: USG Insights",
 "description": "UniFi Poller v2.0 Displays detailed information for security gateways in a UniFi network.",
 "tags": [
  "unifi",
  "usg",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now-5s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "show tag values from \"usg\" with key=\"source\""
   },
   {
    "name": "Site",
    "query": "show tag values from \"usg\" with key=\"site_name\" where source =~ /$Controller$/"
   },
   {
    "name": "host",
    "label": "UniFi USG:",
    "query": "show tag values from \"usg\" with key=\"name\" where site_name =~ /$Site$/"
   }
  ]
 },
 "panels": [
  {
   "title": "USG Details",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Data" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Gateway: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "host" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": {
    "content": "<br>\n<center><b><font size=\"6px\">Unifi USG</font></b></center>\n"
   }
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "speedtest-status_xput_upload" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "uplink_speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Desktop",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "num_desktop" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "user-num_sta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Handheld",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "num_handheld" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Uplink Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "uplink_latency" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "speedtest-status_xput_download" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Guests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "guest-num_sta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Mobile",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "num_mobile" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Networks",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "is_guest" ], "type": "tag" },
      { "params": [ "up" ], "type": "tag" },
      { "params": [ "enabled" ], "type": "tag" },
      { "params": [ "domain_name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "purpose" ], "type": "tag" }
     ],
     "measurement": "usg_networks",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "purpose" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "enabled" ], "type": "tag" },
      { "params": [ "up" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "usg_wan_ports",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "gateway" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "name" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "USG Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "loadavg_1" ], "type": "field" },
       { "params": [ "Avg Load 1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_5" ], "type": "field" },
       { "params": [ "Avg Load 5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_15" ], "type": "field" },
       { "params": [ "Avg Load 15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "graph",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "alias": "$tag_purpose $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "purpose" ], "type": "tag" }
     ],
     "measurement": "usg_wan_ports",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput",
   "type": "graph",
   "description": "Spikes on this graph that do not appear on the WAN graph indicate inter-VLAN-routing. Rx is on the negative axis.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "lan-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "lan-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Packets",
   "type": "graph",
   "description": "PPS on the WAN interface. Rx is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "pps", "label": "packets / second" }
   ],
   "targets": [
    {
     "alias": "$tag_purpose $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "purpose" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usg_wan_ports",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Packets",
   "type": "graph",
   "description": "PPS on the LAN interface. Rx is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps", "label": "packets / second" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "lan-rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "lan-tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Multicast & Broadcast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "pps", "label": "packets / second" }
   ],
   "targets": [
    {
     "alias": "$tag_purpose $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "purpose" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usg_wan_ports",
     "select": [
      [
       { "params": [ "rx_multicast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Multicast Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_multicast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Multicast Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_broadcast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Broadcast Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_broadcast" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Broadcast Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Errors & Drops",
   "type": "graph",
   "description": "May show problems with your WAN interface. Rx is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps", "label": "packets / second" }
   ],
   "targets": [
    {
     "alias": "$tag_purpose $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "purpose" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usg_wan_ports",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Drops",
   "type": "graph",
   "description": "May show problems with your WAN interface. Rx on negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "pps", "label": "packets / second" }
   ],
   "targets": [
    {
     "alias": "$tag_purpose $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "purpose" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usg",
     "select": [
      [
       { "params": [ "lan-rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop Rx" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Purposely Empty Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } }
 ]
}